spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:helowin
    username: yzh
    password: 123456
    thymeleaf:
      encoding:
  mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.demo.parent.userdubboserver
server:
  port: 8080
mapper:
  identity: ORACLE
  mappers: tk.mybatis.mapper.common.Mapper
dubbo:
  application:
    name: user-dubbo-server
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    port: 20887
    name: dubbo
  scan:
    base-packages:  com.demo.parent.userdubboserver

